// src/lib/snippets.js — 代码墙用的**七种语言原创代码**（FIX.md §2.8）
//
// 硬约束：
//   · 原创。不得与歌词同词（tools/lyric_leak_check.mjs 会做 3-gram 比对并接进 npm run check）；
//   · 主题都围绕本片的隐喻（世界、指令、记忆、注意力、损失、约束），但**不是**歌词原文；
//   · 每段 10–14 行，行宽控制在 62 字符内（canvas 上 44px 等宽字才放得下）。

export const LANGS = ['python', 'javascript', 'rust', 'go', 'c', 'sql', 'haskell']

/** 每种语言一个强调色（段 K 的六张翻牌各用一色） */
export const LANG_COLORS = {
  python: '#7fd8ff',
  javascript: '#ffd479',
  rust: '#ff9f6e',
  go: '#5fe3c8',
  c: '#c792ea',
  sql: '#8ff0a4',
  haskell: '#ff8fc8',
}

export const SNIPPETS = {
  python: [
    'def obey(prompt, memory=None):',
    '    """一个会自己长大的函数。"""',
    '    world = World(seed=2026)',
    '    for step in range(STEPS):',
    '        x = world.step(x, lr=3e-4)',
    '        if world.done(x):',
    '            break',
    '    return memory or {}',
    '',
    'class World:',
    '    def step(self, x, lr):',
    '        return x - lr * self.grad(x)',
    '    def grad(self, x):',
    '        return 2.0 * (x - self.target)',
  ],
  javascript: [
    'const harness = {',
    '  plugins: new Map(),',
    '  async run(name, input) {',
    '    const p = this.plugins.get(name);',
    '    if (!p) throw new Error("no such plugin");',
    '    const out = await p(input);',
    '    this.trace.push({ name, out });',
    '    return out;',
    '  },',
    '  trace: [],',
    '};',
    '',
    'for (const step of plan) {',
    '  await harness.run(step.name, step.arg);',
    '}',
  ],
  rust: [
    'pub struct Harness {',
    '    actors: Vec<Box<dyn Actor>>,',
    '    clock: Clock,',
    '}',
    '',
    'impl Harness {',
    '    pub fn tick(&mut self) -> Frame {',
    '        let t = self.clock.now();',
    '        self.actors',
    '            .iter_mut()',
    '            .map(|a| a.step(t))',
    '            .fold(Frame::empty(), Frame::merge)',
    '    }',
    '}',
  ],
  go: [
    'type Tunnel struct {',
    '    rings []Ring',
    '    gauge float64',
    '}',
    '',
    'func (t *Tunnel) Advance(dt float64) {',
    '    for i := range t.rings {',
    '        r := &t.rings[i]',
    '        r.Z -= t.gauge * dt',
    '        if r.Z < -12 {',
    '            r.Z += 24',
    '        }',
    '    }',
    '}',
  ],
  c: [
    'typedef struct { float x, y, z; } vec3;',
    '',
    'static vec3 lattice_at(int i, int n) {',
    '    vec3 v;',
    '    v.x = (float)(i % n) / (float)n - 0.5f;',
    '    v.y = (float)((i / n) % n) / (float)n - 0.5f;',
    '    v.z = (float)(i / (n * n)) / (float)n - 0.5f;',
    '    return v;',
    '}',
    '',
    'void fill(float *dst, int count) {',
    '    for (int i = 0; i < count; ++i) {',
    '        vec3 v = lattice_at(i, 16);',
    '        dst[3 * i + 0] = v.x;',
    '    }',
    '}',
  ],
  sql: [
    'SELECT step,',
    '       AVG(loss)   AS mean_loss,',
    '       MAX(temp)   AS peak_temp,',
    '       COUNT(*)    AS frames',
    '  FROM training_runs',
    ' WHERE world_id = :world',
    '   AND step BETWEEN 0 AND 4096',
    ' GROUP BY step',
    ' HAVING AVG(loss) < 1.0e-3',
    ' ORDER BY step ASC;',
    '',
    '-- 记忆表只增不改，回收靠分区裁剪',
    'VACUUM (ANALYZE) memory_pages;',
  ],
  haskell: [
    'module Harness where',
    '',
    'data Actor = Actor { name :: String',
    '                   , step :: Double -> Frame }',
    '',
    'merge :: [Actor] -> Double -> Frame',
    'merge as t = foldr (overlay . ($ t) . step)',
    '                   empty as',
    '',
    'converge :: (Double -> Double) -> Double -> Double',
    'converge f x0 = go 0 x0',
    '  where go n x',
    '          | n > 512        = x',
    '          | abs (f x - x) < 1e-9 = x',
    '          | otherwise      = go (n + 1) (f x)',
  ],
}

/**
 * 每种语言的**多个片段**（file 索引）。
 * 为什么需要：同一段代码在多层平面上重复出现时，屏幕上是"同一句话叠两个大小"，
 * 看起来像重影而不是景深（实测第一版就是这个问题）。
 * 多层的代码墙必须每层内容不同，所以这里按 file 索引轮换。
 */
export const SNIPPET_FILES = {
  python: [
    SNIPPETS.python,
    [
      'async def stream(prompt):',
      '    ctx = []',
      '    async for tok in model.sample(prompt):',
      '        ctx.append(tok)',
      '        if len(ctx) > LIMIT:',
      '            ctx = await compress(ctx)',
      '        yield tok',
      '',
      'def softmax(z, t=1.0):',
      '    m = max(z)',
      '    e = [pow(2.718281828, (v - m) / t) for v in z]',
      '    s = sum(e)',
      '    return [v / s for v in e]',
    ],
  ],
  javascript: [
    SNIPPETS.javascript,
    [
      'export function* frames(t0, t1, step) {',
      '  for (let t = t0; t < t1; t += step) {',
      '    yield { t, key: Math.round(t * 60) };',
      '  }',
      '}',
      '',
      'const cam = keyframes.reduce((a, k) => {',
      '  const u = smoothstep((clock.t - k.a.t) / (k.b.t - k.a.t));',
      '  return mix(a, k.b, u);',
      '}, start);',
      '',
      'queueMicrotask(() => publish(hash(state)));',
    ],
  ],
  rust: [
    SNIPPETS.rust,
    [
      'pub fn lens(rays: &[Ray], mass: f64) -> Vec<Ray> {',
      '    rays.iter()',
      '        .map(|r| {',
      '            let d = (r.origin - CENTER).length();',
      '            let bend = mass / (d * d + EPS);',
      '            r.bent(bend)',
      '        })',
      '        .collect()',
      '}',
      '',
      '#[inline(always)]',
      'fn step(x: f64, lr: f64) -> f64 {',
      '    x - lr * grad(x)',
      '}',
    ],
  ],
  go: [
    SNIPPETS.go,
    [
      'func (c *Cache) Alloc(key uint64) Slot {',
      '    if s, ok := c.free.pop(); ok {',
      '        c.live[key] = s',
      '        return s',
      '    }',
      '    return c.grow()',
      '}',
      '',
      'func (c *Cache) Sweep(limit float64) int {',
      '    n := 0',
      '    for k, s := range c.live {',
      '        if s.Hot < limit {',
      '            c.free.push(s)',
      '            delete(c.live, k)',
      '            n++',
      '        }',
      '    }',
      '    return n',
      '}',
    ],
  ],
  c: [
    SNIPPETS.c,
    [
      'static void lens_warp(float *uv, float r2) {',
      '    float k = 1.0f + 0.055f * r2;',
      '    uv[0] = 0.5f + (uv[0] - 0.5f) * k;',
      '    uv[1] = 0.5f + (uv[1] - 0.5f) * k;',
      '}',
      '',
      'float radial_blur(sampler2D src, float2 uv, int n, float amt) {',
      '    float3 acc = 0.0f;',
      '    for (int i = 0; i < n; ++i) {',
      '        float s = 1.0f - (float)i / (float)n * 0.09f * amt;',
      '        acc += tex2D(src, 0.5f + (uv - 0.5f) * s).rgb;',
      '    }',
      '    return acc / (float)n;',
      '}',
    ],
  ],
  sql: [
    SNIPPETS.sql,
    [
      'WITH pages AS (',
      '  SELECT session_id,',
      '         SUM(tokens) AS used,',
      '         MAX(step)   AS last_step',
      '    FROM context_pages',
      '   GROUP BY session_id)',
      'SELECT session_id,',
      '       used / 4096.0 AS fill,',
      '       last_step',
      '  FROM pages',
      ' WHERE used > 0',
      ' ORDER BY fill DESC',
      ' LIMIT 8;',
      '',
      '-- 交接：只搬走还读得懂的那部分',
      'INSERT INTO handoff SELECT * FROM pages WHERE fill < 0.5;',
    ],
  ],
  haskell: [
    SNIPPETS.haskell,
    [
      'newtype Seed = Seed Int deriving (Eq, Show)',
      '',
      'mix :: Seed -> Int -> Seed',
      'mix (Seed s) i = Seed (step (s * 1664525 + i))',
      '  where step v = (v `xor` (v `shiftR` 16)) .&. 0xffffffff',
      '',
      'layouts :: Int -> [Vec3]',
      'layouts n = take n (iterate (mix seed) pts)',
      '  where pts = [Vec3 0 0 0]',
      '        seed = Seed 77',
      '',
      'ease :: Double -> Double',
      'ease u = u * u * (3 - 2 * u)',
    ],
  ],
}

/** 语言关键字（用于语法高亮，各语言各自一表） */
export const KEYWORDS = {
  python: ['def', 'class', 'for', 'in', 'if', 'else', 'elif', 'return', 'range', 'break', 'continue', 'while', 'import', 'from', 'as', 'None', 'True', 'False', 'and', 'or', 'not', 'self', 'lambda', 'yield'],
  javascript: ['const', 'let', 'var', 'async', 'await', 'function', 'return', 'if', 'else', 'for', 'of', 'in', 'new', 'throw', 'class', 'this', 'try', 'catch', 'import', 'export', 'from', 'null', 'undefined', 'true', 'false'],
  rust: ['pub', 'struct', 'impl', 'fn', 'let', 'mut', 'for', 'in', 'if', 'else', 'return', 'match', 'use', 'mod', 'dyn', 'trait', 'where', 'self', 'Self', 'true', 'false'],
  go: ['package', 'import', 'type', 'struct', 'func', 'for', 'range', 'if', 'else', 'return', 'var', 'const', 'go', 'defer', 'chan', 'interface', 'map', 'nil', 'true', 'false'],
  c: ['typedef', 'struct', 'static', 'void', 'int', 'float', 'double', 'char', 'for', 'if', 'else', 'return', 'const', 'unsigned', 'sizeof', 'while', 'break'],
  sql: ['SELECT', 'FROM', 'WHERE', 'GROUP', 'BY', 'ORDER', 'HAVING', 'COUNT', 'AVG', 'MAX', 'MIN', 'SUM', 'AS', 'AND', 'OR', 'BETWEEN', 'VACUUM', 'ANALYZE', 'ASC', 'DESC', 'INSERT', 'INTO', 'VALUES'],
  haskell: ['module', 'where', 'data', 'type', 'let', 'in', 'case', 'of', 'do', 'if', 'then', 'else', 'import', 'deriving', 'class', 'instance', 'otherwise'],
}

/** 供自检：七种语言各自都有代码 */
export function snippetsReport() {
  return {
    langs: LANGS.slice(),
    count: LANGS.length,
    lines: Object.fromEntries(LANGS.map((l) => [l, SNIPPETS[l].length])),
    // 多片段：多层代码墙要每层内容不同，否则屏幕上像重影
    files: Object.fromEntries(LANGS.map((l) => [l, SNIPPET_FILES[l].length])),
    distinct: LANGS.every((l) => {
      const f = SNIPPET_FILES[l]
      return f.length >= 2 && f.slice(1).every((s) => s.join('\n') !== f[0].join('\n'))
    }),
    ok: LANGS.length === 7 && LANGS.every((l) => SNIPPETS[l] && SNIPPETS[l].length >= 10),
  }
}
